import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 15,
        paddingVertical: 10,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
        marginTop: 18,
    },
    searchContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f3f4f6',
        borderRadius: 20,
        paddingHorizontal: 10,
        height: 40,
        marginRight: 10,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#1a1a1a',
    },
    iconButton: {
        padding: 8,
        marginLeft: 5,
    },
    content: {
        flex: 1,
    },
    contentText: {
        fontSize: 18,
        color: '#1a1a1a',
    },
    fabWeather: {
        position: 'absolute',
        bottom: 105, // Juste au-dessus de la nav bar
        right: 20,
        backgroundColor: '#0057b7',
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        zIndex: 10,

    },
    bottomNav: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        backgroundColor: '#fff',
    },
    tab: {
        alignItems: 'center',
        padding: 5,
        flex: 1,
    },
    activeTab: {
        backgroundColor: '#f0f9ff',
        borderRadius: 10,
    },
    tabText: {
        fontSize: 10,
        color: '#6b7280',
        marginTop: 4,
    },
    activeTabText: {
        color: '#0057b7',
        fontWeight: '600',
    },
    menuIcon: {
        width: 24,
        height: 24,
        resizeMode: 'contain',
    },
    loadingContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
    },
    logoHeaderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    logo: {
        width: 32,
        height: 32,
        marginRight: 10,
    },
    logoText: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    floatingHeader: {
        position: 'absolute',
        top: 30,
        left: 0,
        right: 0,
        zIndex: 100,
    },
    floatingSearchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        marginHorizontal: 15,
        borderRadius: 24,
        paddingHorizontal: 12,
        height: 48,
    },
    searchLogo: {
        width: 24,
        height: 24,
        borderRadius: 12,
    },
    searchBranding: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 10,
    },
    brandingText: {
        fontSize: 14,
        fontWeight: 'bold',
        marginLeft: 6,
    },
    searchDivider: {
        width: 1,
        height: 24,
        backgroundColor: '#e5e7eb',
        marginRight: 10,
    },
    searchIconBtn: {
        padding: 8,
    },
    quickActionsScroll: {
        marginTop: 12,
    },
    quickActionsContent: {
        paddingHorizontal: 15,
    },
    quickActionBtn: {
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 8,
    },
    quickActionText: {
        fontSize: 14,
        fontWeight: '500',
    },
    shadow: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    mapControlsContainer: {
        position: 'absolute',
        bottom: 25,
        right: 15,
        zIndex: 101,
        flexDirection: 'column',
        alignItems: 'flex-end',
    },
    mapControlButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    placeMarkerContainer: {
        padding: 2,
        backgroundColor: '#fff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1.41,
        elevation: 2,
    },
    placeMarkerImage: {
        width: 40,
        height: 40,
        borderRadius: 6,
    },
    placeMarkerIcon: {
        width: 40,
        height: 40,
        borderRadius: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
    calloutContainer: {
        padding: 5,
        minWidth: 120,
    },
    calloutTitle: {
        fontWeight: 'bold',
        fontSize: 14,
    },
    calloutSub: {
        fontSize: 12,
        color: '#6b7280',
    },
    streetViewHeader: {
        height: 60,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        backgroundColor: '#1a1a1a',
    },
    closeBtn: {
        padding: 8,
    },
    streetViewTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 15,
    },
});
