import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 15,
        paddingVertical: 10,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
        marginTop: 18,
    },
    searchContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f3f4f6',
        borderRadius: 20,
        paddingHorizontal: 10,
        height: 40,
        marginRight: 10,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#1a1a1a',
    },
    iconButton: {
        padding: 8,
        marginLeft: 5,
    },
    content: {
        flex: 1,
    },
    contentText: {
        fontSize: 18,
        color: '#1a1a1a',
    },
    fabWeather: {
        position: 'absolute',
        bottom: 105, // Juste au-dessus de la nav bar
        right: 20,
        backgroundColor: '#0057b7',
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        zIndex: 10,

    },
    bottomNav: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        backgroundColor: '#fff',
    },
    tab: {
        alignItems: 'center',
        padding: 5,
        flex: 1,
    },
    activeTab: {
        backgroundColor: '#f0f9ff',
        borderRadius: 10,
    },
    tabText: {
        fontSize: 10,
        color: '#6b7280',
        marginTop: 4,
    },
    activeTabText: {
        color: '#0057b7',
        fontWeight: '600',
    },
    menuIcon: {
        width: 24,
        height: 24,
        resizeMode: 'contain',
    },
    loadingContainer: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
    },
    logoHeaderContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    logo: {
        width: 32,
        height: 32,
        marginRight: 10,
    },
    logoText: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    floatingHeader: {
        position: 'absolute',
        top: 30,
        left: 0,
        right: 0,
        zIndex: 100,
    },
    floatingSearchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        marginHorizontal: 15,
        borderRadius: 24,
        paddingHorizontal: 12,
        height: 48,
    },
    searchLogo: {
        width: 24,
        height: 24,
        borderRadius: 12,
    },
    searchBranding: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 10,
    },
    brandingText: {
        fontSize: 14,
        fontWeight: 'bold',
        marginLeft: 6,
    },
    searchDivider: {
        width: 1,
        height: 24,
        backgroundColor: '#e5e7eb',
        marginRight: 10,
    },
    searchIconBtn: {
        padding: 8,
    },
    quickActionsScroll: {
        marginTop: 12,
    },
    quickActionsContent: {
        paddingHorizontal: 15,
    },
    quickActionBtn: {
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 8,
    },
    quickActionText: {
        fontSize: 14,
        fontWeight: '500',
    },
    shadow: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 4,
    },
    mapControlsContainer: {
        position: 'absolute',
        bottom: 25,
        right: 15,
        zIndex: 101,
        flexDirection: 'column',
        alignItems: 'flex-end',
    },
    mapControlButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 70,
        marginTop: -40, // ajusté pour placer l'icône GPS un peu plus bas au-dessus de l'icône 3D
    },
    placeMarkerContainer: {
        padding: 2,
        backgroundColor: '#fff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5e7eb',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1.41,
        elevation: 2,
    },
    placeMarkerImage: {
        width: 40,
        height: 40,
        borderRadius: 6,
    },
    placeMarkerIcon: {
        width: 40,
        height: 40,
        borderRadius: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
    calloutContainer: {
        padding: 5,
        minWidth: 120,
    },
    calloutTitle: {
        fontWeight: 'bold',
        fontSize: 14,
    },
    calloutSub: {
        fontSize: 12,
        color: '#6b7280',
    },
    streetViewHeader: {
        height: 60,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        backgroundColor: '#1a1a1a',
    },
    closeBtn: {
        padding: 8,
    },
    streetViewTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        marginLeft: 15,
    },
    // Bottom Sheet Styles
    bottomSheet: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: '100%',
        backgroundColor: '#fff',
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        paddingHorizontal: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 20,
        zIndex: 1000,
    },
    sheetHandleContainer: {
        alignItems: 'center',
        paddingVertical: 12,
    },
    sheetHandle: {
        width: 40,
        height: 5,
        backgroundColor: '#e5e7eb',
        borderRadius: 2.5,
    },
    sheetHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#f3f4f6',
    },
    sheetCityName: {
        fontSize: 20,
        fontWeight: 'bold',
    },
    weatherInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    temperatureText: {
        fontSize: 22,
        fontWeight: 'bold',
        marginLeft: 8,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 25,
        marginBottom: 15,
    },
    listItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
        backgroundColor: 'transparent',
    },
    itemImageContainer: {
        position: 'relative',
        width: 100,
        height: 70,
        borderRadius: 12,
        overflow: 'hidden',
    },
    itemImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    priceBadge: {
        position: 'absolute',
        bottom: 5,
        left: 5,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 6,
    },
    priceText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
    },
    itemInfo: {
        flex: 1,
        marginLeft: 15,
    },
    itemName: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 4,
    },
    itemDistance: {
        fontSize: 14,
        color: '#6b7280',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 25,
        marginBottom: 5,
    },
    sheetContent: {
        flex: 1,
        paddingBottom: 20,
    },
    categorySelectorScroll: {
        marginBottom: 15,
    },
    categorySelectorContent: {
        paddingHorizontal: 15,
    },
    categoryMenuContainer: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        marginBottom: 15,
    },
    categoryTab: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 8,
        alignItems: 'center',
        borderBottomWidth: 3,
        borderBottomColor: 'transparent',
    },
    categoryTabActive: {
        borderBottomColor: '#0057b7',
    },
    categoryTabText: {
        fontSize: 13,
        fontWeight: '500',
    },
    categoryTabTextActive: {
        color: '#0057b7',
        fontWeight: '600',
    },
    categoryBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        marginRight: 8,
        backgroundColor: '#fff',
    },
    categoryBtnActive: {
        backgroundColor: '#0057b7',
    },
    categoryBtnText: {
        fontSize: 13,
        fontWeight: '500',
        marginLeft: 4,
    },
    categoryBtnTextActive: {
        color: '#fff',
    },
    carouselContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 10,
         marginTop: -300,
    },
    imageCard: {
        width: '100%',
        backgroundColor: 'transparent',
        alignItems: 'center',
    },
    blackFrame: {
        width: '100%',
        aspectRatio: 16 / 9,
        backgroundColor: '#000',
        borderRadius: 20,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#374151',
    },
    fullImage: {
        width: '100%',
        height: '100%',
    },
    cardInfo: {
        marginTop: 15,
        alignItems: 'center',
        width: '100%',
    },
    cardTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 6,
        textAlign: 'center',
    },
    cardDistance: {
        fontSize: 16,
        marginBottom: 25,
        textAlign: 'center',
        opacity: 0.8,
    },
    carouselControls: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 30,
        marginTop: 10,
    },
    chevronBtn: {
        padding: 10,
    },
    paginationDots: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    dot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginHorizontal: 4,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 5,
        marginBottom: 10,
    },
    twinCard: {
        width: '48%',
        backgroundColor: 'transparent',
    },
    twinBlackFrame: {
        width: '100%',
        aspectRatio: 1, // Square or slightly portrait as per drawing
        backgroundColor: '#000',
        borderRadius: 15,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#374151',
    },
    twinCardInfo: {
        marginTop: 10,
        paddingHorizontal: 4,
    },
    twinCardTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 2,
    },
    twinCardSub: {
        fontSize: 12,
        marginBottom: 2,
    },
    twinCardDistance: {
        fontSize: 11,
        opacity: 0.7,
    },
    seeAllTrendingBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#f3f4f6',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
        marginTop: 15,
        width: '100%',
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    seeAllTrendingText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6b7280',
        marginRight: 6,
    },
    emptyText: {
        fontSize: 16,
        textAlign: 'center',
    },
});
